services:
    firefox:
        container_name: firefox
        security_opt:
            - seccomp=unconfined
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - FIREFOX_CLI=https://duckduckgo.com/
        ports:
            - 3003:3000
            - 3004:3001
        shm_size: 1gb
        restart: unless-stopped
        image: lscr.io/linuxserver/firefox:latest
